parameters:
#    coaching.example.class: coaching\siteBundle\Example

services:
#    coaching.example:
#        class: %coaching.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
