<?php

namespace coaching\siteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends EntityRepository
{
}
