<?php

namespace coaching\siteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{
}
